import dk.sdu.petni23.gameengine.entity.IEntitySPI;

module Common {
    requires javafx.graphics;
    requires GameEngine;
    requires java.desktop;
    requires java.xml;
    requires com.google.gson;
    exports dk.sdu.petni23.common.shape;
    exports dk.sdu.petni23.common.util;
    exports dk.sdu.petni23.common;
    exports dk.sdu.petni23.common.misc;
    exports dk.sdu.petni23.common.spritesystem;
    exports dk.sdu.petni23.common.world;
    exports dk.sdu.petni23.common.enums;
    exports dk.sdu.petni23.common.components.collision;
    exports dk.sdu.petni23.common.components.movement;
    exports dk.sdu.petni23.common.components.actions;
    exports dk.sdu.petni23.common.components;
    exports dk.sdu.petni23.common.components.gameflow;
    exports dk.sdu.petni23.common.components.health;
    exports dk.sdu.petni23.common.components.rendering;
    exports dk.sdu.petni23.common.components.sound;
    exports dk.sdu.petni23.common.components.items;
    exports dk.sdu.petni23.common.components.inventory;
    exports dk.sdu.petni23.common.components.damage;
    exports dk.sdu.petni23.common.components.shop;
    exports dk.sdu.petni23.common.world.mapgen;
    exports dk.sdu.petni23.common.configreader;
    exports dk.sdu.petni23.common.components.ai;
    exports dk.sdu.petni23.common.sound;
    opens dk.sdu.petni23.common.components.collision to com.google.gson;
    opens dk.sdu.petni23.common.components.movement to com.google.gson;
    opens dk.sdu.petni23.common.components.actions to com.google.gson;
    opens dk.sdu.petni23.common.components to com.google.gson;
    opens dk.sdu.petni23.common.components.health to com.google.gson;
    opens dk.sdu.petni23.common.components.rendering to com.google.gson;
    opens dk.sdu.petni23.common.components.sound to com.google.gson;
    opens dk.sdu.petni23.common.components.items to com.google.gson;
    opens dk.sdu.petni23.common.components.inventory to com.google.gson;
    opens dk.sdu.petni23.common.components.damage to com.google.gson;
    opens dk.sdu.petni23.common.components.shop to com.google.gson;
    opens dk.sdu.petni23.common.world.mapgen to com.google.gson;
    opens dk.sdu.petni23.common.configreader to com.google.gson;
    opens dk.sdu.petni23.common.components.ai to com.google.gson;
    uses IEntitySPI;
}